### PR TITLE
Update for Avalonia 11 RC1 API changes

### LINKED ISSUE #140: Doesn't work on Avalonia 11 RC1
```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'Void Avalonia.Styling.StyleBase.Add(Avalonia.Styling.ISetter)'.
  Source=MessageBox.Avalonia
  StackTrace:
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulate(IServiceProvider , MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.!XamlIlPopulateTrampoline(MsBoxCustomWindow )
   at MessageBox.Avalonia.Views.MsBoxCustomWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxCustomWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxCustomWindow(MessageBoxCustomParams params)
   at Fronter.ViewModels.MainWindowViewModel.<CheckForUpdates>d__70.MoveNext() in D:\GitHub\IhateTrains\Fronter.NET\Fronter.NET\ViewModels\MainWindowViewModel.cs:line 247

```

### PR DESCRIPTION
**Pull request by IhateTrains**
~Does NOT help with https://github.com/AvaloniaCommunity/MessageBox.Avalonia/issues/140, which seems to require a Markdown.Avalonia update.~
EDIT: Also bumps Markdown.Avalonia.Tight, which fixes #140

### CODE REVIEW

**Comment by IhateTrains** [comment]
The PR now also bumps Markdown.Avalonia.Tight, which fixes #140.

**Review by legend2ks — APPROVED** [review]
It seems correct.

**Comment by aldelaro5** [comment]
hey, so I wonder, is this going to get closed?

It seems for some reasons, the pr was implemented in a commit already and a nuget was released. This is why this pr has conflicts so I wonder what is happening with this pr.

**Comment by IhateTrains** [comment]
> It seems for some reasons, the pr was implemented in a commit already and a nuget was released.

Seems incomplete:
https://github.com/AvaloniaCommunity/MessageBox.Avalonia/blob/949b0ae7bdf6582e131cbd71c0538b3c40f36a87/src/MessageBox.Avalonia/ViewModels/Base/AbstractMsBoxViewModel.cs#L80

**Pull request merged**
